server:
  port: 8081

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: ${sky.datasource.driver-class-name}
    url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}
    username: ${sky.datasource.username}
    password: ${sky.datasource.password}
  session:
    timeout: ${sky.jwt.admin-ttl}

mybatis-flex:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 显示数据库日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名
    map-underscore-to-camel-case: true
  global-config:
    logic-delete-column: isDelete
    logic-delete-value: 1
    logic-not-delete-value: 0

knife4j:
  enable: true
  setting:
    language: zh-CN
  openapi:
    title: 匹配系统接口文档
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.rngad33.yxpei.controller
