server:
  port: 8081

spring:
  profiles:
    active: dev
  # 数据库配置
  datasource:
    driver-class-name: ${sky.datasource.driver-class-name}
    url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}
    username: ${sky.datasource.username}
    password: ${sky.datasource.password}
  session:
    store-type: redis
    timeout: ${sky.jwt.admin-ttl}
  # Redis配置
  data:
    redis:
      database: ${sky.redis.database}
      host: ${sky.redis.host}
      port: ${sky.redis.port}
      password: ${sky.redis.password}
      timeout: ${sky.redis.timeout}

mybatis-flex:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 显示数据库日志（注释掉即可关闭日志）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 驼峰命名自动映射
    map-underscore-to-camel-case: true
  global-config:
    logic-delete-column: isDelete
    logic-delete-value: 1
    logic-not-delete-value: 0

knife4j:
  enable: true
  setting:
    language: zh-CN
  openapi:
    title: 匹配系统接口文档
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.rngad33.yxpei.controller
